import { PrismaClient } from '@prisma/client'; import bcrypt from 'bcryptjs';
const db=new PrismaClient();
const permissionCodes=['PROFILE_VIEW','USER_VIEW','USER_MANAGE','USER_ROLE_VIEW','USER_ROLE_ASSIGN','PROPERTY_UNIT_VIEW','PROPERTY_UNIT_MANAGE','PROPERTY_UNIT_VIEW_BASIC','UNIT_GROUP_VIEW','UNIT_GROUP_MANAGE','COMMON_AREA_VIEW','COMMON_AREA_MANAGE','AVAILABILITY_VIEW','RESERVATION_CREATE','RESERVATION_VIEW_OWN','RESERVATION_VIEW_ALL','RESERVATION_VIEW_APPROVED','RESERVATION_CANCEL_OWN','RESERVATION_CANCEL_ALL','GUEST_CREATE_OWN','GUEST_VIEW_OWN','GUEST_DELETE_OWN','GUEST_VIEW_ALL','GUEST_VIEW_AUTHORIZED'] as const;
const matrix={ADMIN:['PROFILE_VIEW','USER_VIEW','USER_ROLE_VIEW','PROPERTY_UNIT_VIEW','PROPERTY_UNIT_MANAGE','UNIT_GROUP_VIEW','UNIT_GROUP_MANAGE','COMMON_AREA_VIEW','COMMON_AREA_MANAGE','AVAILABILITY_VIEW','RESERVATION_VIEW_ALL','RESERVATION_CANCEL_ALL','GUEST_VIEW_ALL'],SECURITY:['PROFILE_VIEW','PROPERTY_UNIT_VIEW_BASIC','COMMON_AREA_VIEW','RESERVATION_VIEW_APPROVED','GUEST_VIEW_AUTHORIZED'],RESIDENT:['PROFILE_VIEW','COMMON_AREA_VIEW','AVAILABILITY_VIEW','RESERVATION_CREATE','RESERVATION_VIEW_OWN','RESERVATION_CANCEL_OWN','GUEST_CREATE_OWN','GUEST_VIEW_OWN','GUEST_DELETE_OWN']} as const;
async function main(){const complex=await db.residentialComplex.upsert({where:{nit:'900-DEMO'},update:{},create:{name:'Conjunto Residencial Demo ConectaPH',nit:'900-DEMO',address:'Dirección de demostración'}});for(const code of permissionCodes)await db.permission.upsert({where:{code},update:{},create:{code,name:code.replaceAll('_',' ')}});for(const code of Object.keys(matrix) as (keyof typeof matrix)[]){const role=await db.role.upsert({where:{code},update:{},create:{code,name:code}});const permissions=await db.permission.findMany({where:{code:{in:[...matrix[code]]}}});await db.rolePermission.createMany({data:permissions.map(p=>({roleId:role.id,permissionId:p.id})),skipDuplicates:true})}
 const towerType=await db.unitGroupType.upsert({where:{name:'Torre'},update:{},create:{name:'Torre'}});await db.unitGroupType.upsert({where:{name:'Cuadra'},update:{},create:{name:'Cuadra'}});const towers=[];for(const n of ['1','2'])towers.push(await db.unitGroup.upsert({where:{complexId_unitGroupTypeId_identifier:{complexId:complex.id,unitGroupTypeId:towerType.id,identifier:n}},update:{},create:{complexId:complex.id,unitGroupTypeId:towerType.id,identifier:n,name:`Torre ${n}`}}));const types=new Map<string,string>();for(const name of ['Apartamento','Casa','Parqueadero']){const t=await db.unitType.upsert({where:{name},update:{},create:{name}});types.set(name,t.id)}
 const units=[];for(const [tower,identifier] of [['1','101'],['1','102'],['2','101'],['2','201']])units.push(await db.propertyUnit.upsert({where:{complexId_unitGroupId_identifier:{complexId:complex.id,unitGroupId:towers[Number(tower)-1]!.id,identifier}},update:{},create:{complexId:complex.id,unitTypeId:types.get('Apartamento')!,unitGroupId:towers[Number(tower)-1]!.id,identifier}}));let parking=await db.propertyUnit.findFirst({where:{complexId:complex.id,unitGroupId:null,identifier:'P-001'}});parking??=await db.propertyUnit.create({data:{complexId:complex.id,unitTypeId:types.get('Parqueadero')!,identifier:'P-001'}});
 for(const area of [{name:'Salón social',capacity:60,openingTime:'08:00',closingTime:'22:00',reservationDurationMinutes:120},{name:'Cancha múltiple',capacity:20,openingTime:'06:00',closingTime:'21:00',reservationDurationMinutes:60}])await db.commonArea.upsert({where:{complexId_name:{complexId:complex.id,name:area.name}},update:{},create:{complexId:complex.id,...area}});
 const hash=await bcrypt.hash('ConectaPH2026!',12);for(const u of [{email:'residente@conectaph.local',firstName:'Rosa',lastName:'Residente',role:'RESIDENT'},{email:'administrador@conectaph.local',firstName:'Ana',lastName:'Administradora',role:'ADMIN'},{email:'vigilancia@conectaph.local',firstName:'Víctor',lastName:'Vigilancia',role:'SECURITY'}]){const user=await db.user.upsert({where:{email:u.email},update:{passwordHash:hash},create:{email:u.email,firstName:u.firstName,lastName:u.lastName,passwordHash:hash}});const role=await db.role.findUniqueOrThrow({where:{code:u.role}});await db.userRole.upsert({where:{userId_roleId_complexId:{userId:user.id,roleId:role.id,complexId:complex.id}},update:{active:true},create:{userId:user.id,roleId:role.id,complexId:complex.id}});if(u.role==='RESIDENT')await db.userPropertyUnit.upsert({where:{userId_propertyUnitId_relationshipType:{userId:user.id,propertyUnitId:units[0]!.id,relationshipType:'RESIDENT'}},update:{active:true,isPrimary:true},create:{userId:user.id,propertyUnitId:units[0]!.id,relationshipType:'RESIDENT',active:true,isPrimary:true}})} }
main().finally(()=>db.$disconnect());
